# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  repository_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
    - run: docker pull satackey/action-google-drive:latest
    - run: docker rmi satackey/action-google-drive:latest
      
    - run: docker pull satackey/action-google-drive:latest
    - run: docker rmi satackey/action-google-drive:latest
      
    - run: docker pull satackey/action-google-drive:latest
    - run: docker rmi satackey/action-google-drive:latest
      
    - run: docker pull satackey/action-google-drive:latest
    - run: docker rmi satackey/action-google-drive:latest
      
    - run: docker pull satackey/action-google-drive:latest
    - run: docker rmi satackey/action-google-drive:latest
      
    - run: docker pull satackey/action-google-drive:latest
    - run: docker rmi satackey/action-google-drive:latest
      
    - run: docker pull satackey/action-google-drive:latest
    - run: docker rmi satackey/action-google-drive:latest
      
    - run: docker pull satackey/action-google-drive:latest
    - run: docker rmi satackey/action-google-drive:latest
      
    - run: docker pull satackey/action-google-drive:latest
    - run: docker rmi satackey/action-google-drive:latest
      
    - run: docker pull satackey/action-google-drive:latest
    - run: docker rmi satackey/action-google-drive:latest
      
    - run: docker pull satackey/action-google-drive:latest
    - run: docker rmi satackey/action-google-drive:latest

    - run: docker login docker.pkg.github.com -u x-access-token -p ${{ github.token }}     

    - run: docker pull docker.pkg.github.com/satackey/action-google-drive/github-action-image:66957d3772bf2e452ae3cdc5f676adea1df45eae
    - run: docker rmi docker.pkg.github.com/satackey/action-google-drive/github-action-image:66957d3772bf2e452ae3cdc5f676adea1df45eae
    - run: docker pull docker.pkg.github.com/satackey/action-google-drive/github-action-image:66957d3772bf2e452ae3cdc5f676adea1df45eae
    - run: docker rmi docker.pkg.github.com/satackey/action-google-drive/github-action-image:66957d3772bf2e452ae3cdc5f676adea1df45eae
    - run: docker pull docker.pkg.github.com/satackey/action-google-drive/github-action-image:66957d3772bf2e452ae3cdc5f676adea1df45eae
    - run: docker rmi docker.pkg.github.com/satackey/action-google-drive/github-action-image:66957d3772bf2e452ae3cdc5f676adea1df45eae
    - run: docker pull docker.pkg.github.com/satackey/action-google-drive/github-action-image:66957d3772bf2e452ae3cdc5f676adea1df45eae
    - run: docker rmi docker.pkg.github.com/satackey/action-google-drive/github-action-image:66957d3772bf2e452ae3cdc5f676adea1df45eae
    - run: docker pull docker.pkg.github.com/satackey/action-google-drive/github-action-image:66957d3772bf2e452ae3cdc5f676adea1df45eae
    - run: docker rmi docker.pkg.github.com/satackey/action-google-drive/github-action-image:66957d3772bf2e452ae3cdc5f676adea1df45eae
    - run: docker pull docker.pkg.github.com/satackey/action-google-drive/github-action-image:66957d3772bf2e452ae3cdc5f676adea1df45eae
    - run: docker rmi docker.pkg.github.com/satackey/action-google-drive/github-action-image:66957d3772bf2e452ae3cdc5f676adea1df45eae
    - run: docker pull docker.pkg.github.com/satackey/action-google-drive/github-action-image:66957d3772bf2e452ae3cdc5f676adea1df45eae
    - run: docker rmi docker.pkg.github.com/satackey/action-google-drive/github-action-image:66957d3772bf2e452ae3cdc5f676adea1df45eae
    - run: docker pull docker.pkg.github.com/satackey/action-google-drive/github-action-image:66957d3772bf2e452ae3cdc5f676adea1df45eae
    - run: docker rmi docker.pkg.github.com/satackey/action-google-drive/github-action-image:66957d3772bf2e452ae3cdc5f676adea1df45eae
    - run: docker pull docker.pkg.github.com/satackey/action-google-drive/github-action-image:66957d3772bf2e452ae3cdc5f676adea1df45eae
    - run: docker rmi docker.pkg.github.com/satackey/action-google-drive/github-action-image:66957d3772bf2e452ae3cdc5f676adea1df45eae
    - run: docker pull docker.pkg.github.com/satackey/action-google-drive/github-action-image:66957d3772bf2e452ae3cdc5f676adea1df45eae
    - run: docker rmi docker.pkg.github.com/satackey/action-google-drive/github-action-image:66957d3772bf2e452ae3cdc5f676adea1df45eae
