# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  repository_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - run: echo ${{ github.token }} | docker login docker.pkg.github.com -u x-access-token --password-stdin
    
      
    - run: docker pull docker.pkg.github.com/satackey/github-actions-test/test-packages-registry:scratch-random-of-128mb
    - run: docker rmi docker.pkg.github.com/satackey/github-actions-test/test-packages-registry:scratch-random-of-128mb
        
    - run: docker pull docker.pkg.github.com/satackey/github-actions-test/test-packages-registry:scratch-random-of-128mb
    - run: docker rmi docker.pkg.github.com/satackey/github-actions-test/test-packages-registry:scratch-random-of-128mb
        
    - run: docker pull docker.pkg.github.com/satackey/github-actions-test/test-packages-registry:scratch-random-of-128mb
    - run: docker rmi docker.pkg.github.com/satackey/github-actions-test/test-packages-registry:scratch-random-of-128mb
            
