
name: Test run script from output
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Runs a single command using the runners shell
    - uses: actions/github-script@0.9.0
      id: script
      with:
        script: |
          core.setOutput(`foo`, `
            echo Add other actions to build,
            echo test, and deploy your project.
          `)
    - name: Run a script from output
      run: ${{ steps.script.output.foo }}
