name: CI

on:
  push:
    paths-ignore:
    - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      with:
        path: /home/runner/work/_temp/_github_home/.skicka.metadata.cache
        key: skicka-metadata-${{ github.sha }}
        restore-keys: |
          skicka-metadata-

    - run: ls -al /home/runner/work/_temp/_github_home/
      continue-on-error: true

    - uses: satackey/action-google-drive@v1
      with:
        skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
        download-from: /test
        download-to: /

    - run: |
        ls -al /home/runner/work/_temp/_github_home/
        sudo chown -R $(id -u):$(id -g) /home/runner/work/_temp/_github_home/.skicka.metadata.cache
      continue-on-error: true
