name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: satackey/action-google-drive@release-enable-downloads
      with:
        skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
        download-from: /教材
        download-to: ./
    
    - run: ls -al /教材
