name: CI

on:
  push:
    paths-ignore:
    - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v2
      id: dynamic_step
      with:
        script: |
          return [
            {
              run: 'echo dynamic step is working!!'
            }
          ]

    outputs:
      dynamic_step: ${{ steps.dynamic_step.outputs.result }}

  dynamic_step_job:
    needs: [build]
    runs-on: ubuntu-latest
    steps: ${{ needs.build.outputs.dynamic_step }}
    
